### ISSUE TITLE
Add `v1` tag which tracks the latest `v1.x.x` version

### ISSUE THREAD

**Issue by ForsakenHarmony** [metalbear-co/sccache-action#12]
`uses: metalbear-co/sccache-action@v1` currently errors

**Comment by aviramha** [comment]
Thanks for reporting this. Do you mind sending a PR?

**Comment by ForsakenHarmony** [comment]
This can't be done in a PR, you have to set the tag on https://github.com/metalbear-co/sccache-action/commit/3ff0a5541a0f6b5e2056f1d2b6f014f6fd0f7a3c (and update it on future release commits)

**Comment by aviramha** [comment]
You can tag in CI.
https://github.com/marketplace/actions/github-tag
