### ISSUE TITLE
Download latest release

### ISSUE THREAD

**Issue by rajivshah3** [metalbear-co/sccache-action#4]
Hi! This looks great and I've actually been working on something similar so I'd love to contribute. I noticed this comment:

https://github.com/metalbear-co/sccache-action/blob/91e58973d3f1c9d27d9ae48be6500f687a725fbd/src/main.ts#L9

Using the GitHub API, it's possible to determine the latest version of `sccache` and download the corresponding binary. Would you be ok if I contributed this in a PR?

**Comment by aviramha** [comment]
That's awesome! Feel free to open a PR.
You can also remove the "patch" to use my fork binaries now that I see they released a working version!
